### ISSUE TITLE
:GHDashboard error

### ISSUE THREAD

**Issue by justinmk** [junegunn/vim-github-dashboard#11]
`:GHDashboard` gives me this error after entering my username/password. Not sure if I entered the wrong password or something, but any subsequent attempts to invoke do not ask for the password, and give the same error.

`:GHActivity` seems to work.

```
Error detected while processing function github_dashboard#open:
line   52:
E605: Exception not caught: Error: Vim(echoerr):no implicit conversion of nil into String

```

**Comment by webfd** [comment]
i have a this question, do you help soulution it; thanks
