### ISSUE TITLE
Define mappings before setting the filetype

### ISSUE THREAD

**Issue by itchyny** [junegunn/vim-github-dashboard#17]
Please define mappings before setting the filetype so that we can disable the default mappings
```vim
augroup ghd-mapping
  autocmd!
  autocmd FileType github-dashboard nunmap <buffer> q
augroup END
```

**Comment by junegunn** [comment]
Updated. Could you check it if works for you?

**Comment by itchyny** [comment]
Thanks for quick response. I confirmed :+1:
