### ISSUE TITLE
New mappings <Tab> and <S-Tab> to explorer the links?

### ISSUE THREAD

**Issue by itchyny** [junegunn/vim-github-dashboard#19]
As title, like browsers.

**Comment by junegunn** [comment]
Oh, actually it was replaced by CTRL-N and CTRL-P recently by the following PR: https://github.com/junegunn/vim-github-dashboard/pull/13
I liked tab and s-tab, but I couldn't disagree with the argument.
We could provide `<Plug>` mappings, but I'm not sure how many will actually use them
