### ISSUE TITLE
will the plugin support neovim ?

### ISSUE THREAD

**Issue by wsdjeg** [junegunn/vim-github-dashboard#24]
@junegunn I have tested this plugin in vim .It is great ,but I want to use is in neovim ,will the plugin support neovim , as I know the neovim now does not support ` has('ruby')`

**Comment by junegunn** [comment]
In Soviet Russia, Neovim supports this plugin :)

I mean seriously, I'm not going to rewrite this plugin just to make it run on neovim. Hopefully someday Neovim will add Ruby support and it will work then.

**Comment by hew** [comment]
This plugin works on Neovim (with the ruby plugin) - but you can't open any links.
