### ISSUE TITLE
Loading :GHActivity results in a 404

### ISSUE THREAD

**Issue by mdespuits** [junegunn/vim-github-dashboard#25]
Ran into this problem this morning when running `:GHActivity`

```
Error detected while processing function <SNR>3_lod_cmd[2]..github_dashboard#open:
line   52:
E605: Exception not caught: Error: Vim(echoerr):Not Found (404)
```

I just created a new personal token to use for this, so I'm not entirely sure what is going on. I'm hesitant to say that Github changed it's API, but a 404 seems strange. I get a similar 404 for `:GHDashboard`.

Let me know if I can provide any more context. Thanks!

**Comment by junegunn** [comment]
That's strange. You're accessing public GitHub right? How about `:GHA!` (bang version with no authentication)? Does it work?

**Comment by mdespuits** [comment]
> You're accessing public GitHub right?

You're asking about public vs enterprise, right? If so, yes. it's just github.com.

> How about :GHA! (bang version with no authentication)?

`:GHA!` does not work. I get the same result.

**Comment by mdespuits** [comment]
Hold on, it seems I've having bad credential problems. I'm going to try to resolve those and report back here. Thanks for your help!

**Comment by mdespuits** [comment]
My apologies. I changed my username yesterday and forgot part of the authentication process is the username. All is well again.

:+1:
